### ISSUE TITLE
IndexError: "The shape of the mask[1, 1, 1444, 1620] at index 1 does not match the shape of the indexed tensor[1, 3, 2336, 3504] at index 1]"

### ISSUE THREAD

**Issue by GDhandsome** [rmaphoh/Learning-AVSegmentation#1]
Thank you very much for your code! But I encountered a problem here. I used LES-AV dataset for training. After the training, the following error occurred when I ran test.sh, is there any solution?
![image](https://user-images.githubusercontent.com/70613420/123530626-29d21280-d72f-11eb-8b30-0486108fc643.png)

**Comment by rmaphoh** [comment]
Thanks. The issue has been corrected.

**Comment by GDhandsome** [comment]
Thanks

> Thanks. The issue has been corrected.
