### ISSUE TITLE
Are the two classes（ crossing and uncertainty） considered the same class（uncertainty） in calculating metrics?

### ISSUE THREAD

**Issue by icyclv** [rmaphoh/Learning-AVSegmentation#2]
Hi，Thanks for your work.
    I was a little confused that are the two classes（ crossing and uncertainty in AV-DRIVE） considered the same class（uncertainty） in calculating metrics? 
    Looking forward to your reply.

**Comment by icyclv** [comment]
And I think it's more appropriate to combine the two classes as a crossing class because green seems to refer to  crossing class rather than  uncertainty class.

**Comment by rmaphoh** [comment]
> 

Thanks for your question. Different datasets show various annotation rules for the crossing and some uncertain vessel pixels in the region of optic disc. For DRIVE-AV (https://medicine.uiowa.edu/eye/rite-dataset), they use white colour for uncertain pixels and green for crossing, while LES-AV annotates both uncertain and crossing pixels as green colour. Actually, these crossing pixels are kind of uncertain pixels as the retinal fundus photograph, as 2D image, cannot provide discriminating information to identify the category of the cross pixels.

**Comment by icyclv** [comment]
I really appreciate your help！
