### ISSUE TITLE
Quention about the preprocess code 

### ISSUE THREAD

**Issue by icyclv** [rmaphoh/Learning-AVSegmentation#3]
https://github.com/rmaphoh/Learning-AVSegmentation/blob/e266c61f7ff7caf0b5f5f5f3d1188cae800ab8d6/scripts/dataset.py#L91

Hi，I have a question in the preprocess code. In my opinion,it should add '()' 
`img_array=(img_array-1.0*mean)/(1.0*std)`
Could you please tell me whether I misunderstood or this is a bug?

**Comment by rmaphoh** [comment]
Thanks for your detailed question. It is an empirically experimental setting which contributes to the reproducible performance. This might not be the optimal setting - you can adjust to your customised processing by changing the normalisation and augmentation.

**Comment by icyclv** [comment]
Thank you for your patient reply！And the original settings seem to work better
