### ISSUE TITLE
The program won't work

### ISSUE THREAD

**Issue by lichenghui1476529913** [rmaphoh/Learning-AVSegmentation#4]
Hi，Thanks for your work.
There is a bug in line 105 of the train.py file, the number of dims don't match in permute, may I ask how to solve it? thank you.

**Comment by rmaphoh** [comment]
Hi, could you show the error in running? Thanks.

**Comment by lichenghui1476529913** [comment]
That's line 105 encode_tensor=encoder_tensor.permute(0,3,1,2).contiguous(), showing the number of dims don't match in permute error, And encode_tensor is （6,3,720,800,4）.

**Comment by rmaphoh** [comment]
Thanks for your reminder. We have now rectified the code and data.

**Comment by lichenghui1476529913** [comment]
Hello, thank you for your answer, I can train now, but you changed all the labels to black background, how should I train?

**Comment by rmaphoh** [comment]
They are standard multi-class labels, ranging from 0 to 3 in each pixel where 0 indicates background, 1 artery, 2 vein, and 3 uncertain pixel.

**Comment by lichenghui1476529913** [comment]
Ok, thank you for your answer. I will make the label drawing by myself
